apiVersion: v2
name: benias-game
description: A Helm chart for the Benias party game
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Benias Team
home: https://github.com/BeniMori8/alias-for-friends
keywords:
  - game
  - react
  - nginx
