apiVersion: v1
kind: Service
metadata:
  name: benias-game-service
  labels:
    app: benias-game
spec:
  type: LoadBalancer  # Use NodePort if no cloud load balancer available
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: benias-game
